name: Traffic Light CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          components: rust-src

      - name: Build
        run: cargo +nightly build

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v2
        with:
          name: esp32_traffic_lights_rs
          path: target/riscv32imc-unknown-none-elf/debug/esp32_traffic_lights_rs

      - name: Test Traffic Light Scenario on Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: /
          scenario: 'traffic_light.test.yaml'
